//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteHatSec.Localization.Culture.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageLog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageLog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhiteHatSec.Localization.Culture.Resource.MessageLog", typeof(MessageLog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Failed!.
        /// </summary>
        public static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Failed! Please Enter Correct Credential..
        /// </summary>
        public static string AuthenticationFailedPleaseEnterCorrectCredential {
            get {
                return ResourceManager.GetString("AuthenticationFailedPleaseEnterCorrectCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Failed!Please Enter Correct Server Detail..
        /// </summary>
        public static string AuthenticationFailedPleaseEnterCorrectServerDetail {
            get {
                return ResourceManager.GetString("AuthenticationFailedPleaseEnterCorrectServerDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse File.
        /// </summary>
        public static string BrowseFile {
            get {
                return ResourceManager.GetString("BrowseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Timeout!.
        /// </summary>
        public static string ConnectionTimeout {
            get {
                return ResourceManager.GetString("ConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid URL..
        /// </summary>
        public static string EnterAValidURL {
            get {
                return ResourceManager.GetString("EnterAValidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse json..
        /// </summary>
        public static string FailedToParseJson {
            get {
                return ResourceManager.GetString("FailedToParseJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to post Question..
        /// </summary>
        public static string FailedToPostQuestion {
            get {
                return ResourceManager.GetString("FailedToPostQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Upload Project..
        /// </summary>
        public static string FailedToUploadProject {
            get {
                return ResourceManager.GetString("FailedToUploadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is empty..
        /// </summary>
        public static string FileIsEmpty {
            get {
                return ResourceManager.GetString("FileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import proper json file..
        /// </summary>
        public static string ImportProperJsonFile {
            get {
                return ResourceManager.GetString("ImportProperJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not able to match line and method..
        /// </summary>
        public static string NotAbleToMatchLineAndMethod {
            get {
                return ResourceManager.GetString("NotAbleToMatchLineAndMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not able to match line. But able to find match for method..
        /// </summary>
        public static string NotAbleToMatchLineButAbleToFindMatchForMethod {
            get {
                return ResourceManager.GetString("NotAbleToMatchLineButAbleToFindMatchForMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Credential Detail..
        /// </summary>
        public static string PleaseEnterCredentialDetail {
            get {
                return ResourceManager.GetString("PleaseEnterCredentialDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Question..
        /// </summary>
        public static string PleaseEnterQuestion {
            get {
                return ResourceManager.GetString("PleaseEnterQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Server Detail..
        /// </summary>
        public static string PleaseEnterServerDetail {
            get {
                return ResourceManager.GetString("PleaseEnterServerDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Server to Upload Project..
        /// </summary>
        public static string PleaseEnterServerToUploadProject {
            get {
                return ResourceManager.GetString("PleaseEnterServerToUploadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project is uploaded sucessfully..
        /// </summary>
        public static string ProjectIsUploadedSucessfully {
            get {
                return ResourceManager.GetString("ProjectIsUploadedSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question has been successfully posted..
        /// </summary>
        public static string QuestionIsPosted {
            get {
                return ResourceManager.GetString("QuestionIsPosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require to browse file :.
        /// </summary>
        public static string RequireToBrowseFile {
            get {
                return ResourceManager.GetString("RequireToBrowseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAST Vulnerability Warning.
        /// </summary>
        public static string SASTVulnerabilityWarning {
            get {
                return ResourceManager.GetString("SASTVulnerabilityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select An App..
        /// </summary>
        public static string SelectAnApp {
            get {
                return ResourceManager.GetString("SelectAnApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select App.
        /// </summary>
        public static string SelectApp {
            get {
                return ResourceManager.GetString("SelectApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected filename is different then row pointed file.
        /// </summary>
        public static string SelectedFilenameIsDifferentThenRowPointedFile {
            get {
                return ResourceManager.GetString("SelectedFilenameIsDifferentThenRowPointedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ToDate greater than FromDate..
        /// </summary>
        public static string SelectToDateGreaterThanFromDate {
            get {
                return ResourceManager.GetString("SelectToDateGreaterThanFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentinel IDE Plugin.
        /// </summary>
        public static string SentinelIDEPlugin {
            get {
                return ResourceManager.GetString("SentinelIDEPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentinel login required..
        /// </summary>
        public static string SentinelLoginRequired {
            get {
                return ResourceManager.GetString("SentinelLoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no project to upload..
        /// </summary>
        public static string ThereIsNoProjectToUpload {
            get {
                return ResourceManager.GetString("ThereIsNoProjectToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vulns found.
        /// </summary>
        public static string VulnsFound {
            get {
                return ResourceManager.GetString("VulnsFound", resourceCulture);
            }
        }

        public static string EmptyorInvalidUrl
        {
            get
            {
                return ResourceManager.GetString("EmptyorInvalidUrl", resourceCulture);
            }
        }
    }
}
